import os


KAFKA_BOOTSTRAP_SERVERS = os.getenv(
    "KAFKA_BOOTSTRAP_SERVERS",
    "localhost:9092",
)

KAFKA_POLICY_PROPOSED_TOPIC = os.getenv(
    "KAFKA_POLICY_PROPOSED_TOPIC",
    "POLICY_PROPOSED",
)

KAFKA_LOGICAL_TASK_PROPOSED_TOPIC = os.getenv(
    "KAFKA_LOGICAL_TASK_PROPOSED_TOPIC",
    "LOGICAL_TASK_PROPOSED",
)

KAFKA_LOGICAL_TASK_FAULT_TOPIC = os.getenv(
    "KAFKA_LOGICAL_TASK_FAULT_TOPIC",
    "LOGICAL_TASK_FAULT",
)

KAFKA_POLICY_FAULT_TOPIC = os.getenv(
    "KAFKA_POLICY_FAULT_TOPIC",
    "POLICY_FAULT",
)