"""create logical task registry

Revision ID: 2be75715f63e
Revises: 6c68ffbef820
Create Date: 2026-08-19 17:06:10.250494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2be75715f63e'
down_revision: Union[str, Sequence[str], None] = '6c68ffbef820'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logical_task_registry',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('intent_id', sa.UUID(), nullable=False),
    sa.Column('task_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parameters_to_monitor', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_by', sa.String(length=100), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.alter_column('logical_tasks', 'generated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logical_tasks', 'generated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_table('logical_task_registry')
    # ### end Alembic commands ###
