"""create logical tasks

Revision ID: 6c68ffbef820
Revises: 
Create Date: 2026-08-19 16:41:03.090747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c68ffbef820'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logical_tasks',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('intent_id', sa.UUID(), nullable=False),
    sa.Column('task_description', sa.Text(), nullable=False),
    sa.Column('task_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parameters_to_monitor', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_by', sa.String(length=100), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('try_number', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('task_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logical_tasks')
    # ### end Alembic commands ###
